version: "2.4"
services:
  zookeeper-1:
    container_name: zookeeper-1
    image: confluentinc/cp-zookeeper:7.0.0
    volumes:
      - data-zookeeper-1:/var/lib/zookeeper/data
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka-1:
    image: confluentinc/cp-kafka:7.0.0
    container_name: kafka-1
    volumes:
      - data-broker-1:/var/lib/kafka/data
      - ./jmx-exporter:/usr/share/jmx_exporter/
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:29092,PLAINTEXT_HOST://${DOCKER_HOST_IP}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OPTS: -javaagent:/usr/share/jmx_exporter/jmx_prometheus_javaagent-0.16.1.jar=1234:/usr/share/jmx_exporter/jmx_config_kafka.yml

  schema-registry:
    image: confluentinc/cp-schema-registry:7.0.0
    container_name: schema-registry
    ports:
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka-1:29092

  prometheus:
    image: prom/prometheus:v2.31.1
    volumes:
      - data-prometheus:/prometheus
      - ./prometheus/:/etc/prometheus/
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:8.3.0
    volumes:
      - data-grafana:/var/lib/grafana
    ports:
      - 3000:3000

volumes:
  data-zookeeper-1: {}
  data-broker-1: {}
  data-prometheus: {}
  data-grafana: {}
